import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Check, Zap, ShieldCheck } from "lucide-react";
import { Header } from "@/components/ui/header";
import { Footer } from "@/components/ui/footer";
import { CITATION_STYLES } from "@/lib/citation-styles";
import { generateCitation } from "@/lib/citation-engine";
import { STYLE_SEO, SEO_SAMPLES, SOURCE_SEO, slugToStyle } from "@/lib/style-seo";

export function generateStaticParams() {
  return Object.values(STYLE_SEO).map((s) => ({ slug: s.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const style = slugToStyle[slug];
  if (!style) return { title: "Citation Style — CitePlex" };
  const seo = STYLE_SEO[style];
  const title = `${seo.keyword} — Free, Fast & Accurate | CitePlex`;
  return {
    title,
    description: seo.blurb,
    keywords: [seo.keyword.toLowerCase(), `${seo.slug} citation`, `${seo.slug} format`, `${seo.slug} reference generator`],
    alternates: { canonical: `/styles/${seo.slug}` },
    openGraph: { title, description: seo.blurb, type: "website" },
  };
}

function toHTML(text: string) {
  return text.replace(/\*(.*?)\*/g, "<em>$1</em>");
}

export default async function StyleLandingPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const style = slugToStyle[slug];
  if (!style) notFound();

  const seo = STYLE_SEO[style];
  const meta = CITATION_STYLES[style];
  const examples = SEO_SAMPLES.map((s) => ({
    label: s.label,
    result: generateCitation(s.data, style),
  }));

  const inTextLabel =
    style === "bluebook" ? "Short form" : style === "chicago" || style === "turabian" ? "Footnote" : "In-text";

  return (
    <div className="flex min-h-full flex-col">
      <Header />

      <main className="flex-1">
        {/* Hero */}
        <section className="border-b border-border bg-muted/20">
          <div className="mx-auto max-w-4xl px-6 py-16 lg:px-8 lg:py-20">
            <div className="mb-4 flex items-center gap-2">
              <span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: meta.color }} />
              <span className="text-[13px] font-medium text-muted-foreground">{meta.label}</span>
            </div>
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">{seo.keyword}</h1>
            <p className="mt-4 max-w-2xl text-lg text-muted-foreground">{seo.blurb}</p>
            <div className="mt-7 flex flex-wrap items-center gap-3">
              <Link
                href={`/generate?style=${style}`}
                className="inline-flex items-center gap-1.5 rounded-full bg-foreground px-5 py-2.5 text-[14px] font-medium text-background transition-all hover:opacity-80"
              >
                Generate {meta.label.split(" ")[0]} citations
                <ArrowRight className="h-4 w-4" />
              </Link>
              <div className="flex items-center gap-4 text-[13px] text-muted-foreground">
                <span className="inline-flex items-center gap-1.5"><Zap className="h-3.5 w-3.5" /> Instant</span>
                <span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-3.5 w-3.5" /> No ads</span>
              </div>
            </div>
          </div>
        </section>

        {/* Examples */}
        <section className="mx-auto max-w-4xl px-6 py-16 lg:px-8">
          <h2 className="text-2xl font-bold tracking-tight">How to cite in {meta.label.split(" ")[0]}</h2>
          <p className="mt-2 text-muted-foreground">
            Real examples generated by our {meta.label.split(" ")[0]} engine for the most common source types.
          </p>

          <div className="mt-8 space-y-4">
            {examples.map((ex) => (
              <div key={ex.label} className="rounded-2xl border border-border bg-background overflow-hidden">
                <div className="border-b border-border bg-muted/30 px-5 py-3">
                  <span className="text-sm font-semibold">{ex.label}</span>
                </div>
                <div className="space-y-4 p-5">
                  <div>
                    <p className="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">
                      Reference entry
                    </p>
                    <p
                      className="citation-text pl-8 -indent-8 text-sm leading-relaxed"
                      dangerouslySetInnerHTML={{ __html: toHTML(ex.result.formatted) }}
                    />
                  </div>
                  <div className="border-t border-border pt-4">
                    <p className="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">
                      {inTextLabel}
                    </p>
                    <p
                      className="citation-text text-sm leading-relaxed text-muted-foreground"
                      dangerouslySetInnerHTML={{ __html: toHTML(ex.result.inText) }}
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Disciplines */}
        <section className="border-t border-border bg-muted/20">
          <div className="mx-auto max-w-4xl px-6 py-14 lg:px-8">
            <h2 className="text-2xl font-bold tracking-tight">Who uses {meta.label.split(" ")[0]}?</h2>
            <div className="mt-5 flex flex-wrap gap-2">
              {seo.disciplines.map((d) => (
                <span
                  key={d}
                  className="inline-flex items-center gap-1.5 rounded-full px-3.5 py-1.5 text-sm font-medium"
                  style={{ backgroundColor: `${meta.color}15`, color: meta.color }}
                >
                  <Check className="h-3.5 w-3.5" />
                  {d}
                </span>
              ))}
            </div>
          </div>
        </section>

        {/* Per-source guides */}
        <section className="mx-auto max-w-4xl px-6 pt-14 lg:px-8">
          <h2 className="text-2xl font-bold tracking-tight">
            Cite specific sources in {meta.label.split(" ")[0]}
          </h2>
          <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">
            {Object.values(SOURCE_SEO).map((s) => (
              <Link
                key={s.slug}
                href={`/cite/${s.slug}/${seo.slug}`}
                className="group flex items-center justify-between rounded-xl border border-border bg-background px-4 py-3 text-sm font-medium transition-colors hover:border-primary/40"
              >
                {s.label}
                <ArrowRight className="h-3.5 w-3.5 text-muted-foreground transition-transform group-hover:translate-x-0.5" />
              </Link>
            ))}
          </div>
        </section>

        {/* FAQ */}
        <section className="mx-auto max-w-3xl px-6 py-16 lg:px-8">
          <h2 className="mb-8 text-2xl font-bold tracking-tight">{meta.label.split(" ")[0]} FAQ</h2>
          <div className="space-y-5">
            {seo.faqs.map((f) => (
              <div key={f.q} className="rounded-xl border border-border bg-background p-6">
                <h3 className="font-semibold">{f.q}</h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{f.a}</p>
              </div>
            ))}
          </div>

          <div className="mt-10 rounded-2xl border border-border bg-muted/30 p-8 text-center">
            <h3 className="text-lg font-bold">Ready to cite in {meta.label.split(" ")[0]}?</h3>
            <p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">
              Generate accurate {meta.label} citations in seconds — free, no ads, no sign-up required.
            </p>
            <Link
              href={`/generate?style=${style}`}
              className="mt-5 inline-flex items-center gap-1.5 rounded-full bg-foreground px-5 py-2.5 text-[14px] font-medium text-background transition-all hover:opacity-80"
            >
              Start citing
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </section>

        {/* FAQ structured data for rich results */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: seo.faqs.map((f) => ({
                "@type": "Question",
                name: f.q,
                acceptedAnswer: { "@type": "Answer", text: f.a },
              })),
            }),
          }}
        />
      </main>

      <Footer />
    </div>
  );
}
